find '$HOME/Library/LaunchAgents/' \( -name '*.app' -o -name '*.plist' \)
find '$HOME/Library/Application Support/' \( -name '*.app' -o -name '*.plist' \)
find '$HOME/Applications/' \( -name '*.app' -o -name '*.plist' \)
find '/Library/LaunchAgents/' \( -name '*.app' -o -name '*.plist' \)
find '/Library/LaunchDaemons' \( -name '*.app' -o -name '*.plist' \)
find '/Library/StartupItems/' \( -name '*.app' -o -name '*.plist' \)
find '/Library/Internet Plug-Ins/' \( -name '*.app' -o -name '*.plist' \)
find '/Library/Application Support/' \( -name '*.app' -o -name '*.plist' \)
find '/Applications/' \( -name '*.app' -o -name '*.plist' \)
find '/Developer/Applications/' \( -name '*.app' -o -name '*.plist' \)

