#!/usr/bin/env bash
# options
# WORKSTATION_UPDATE=true
# HACK_MY_OSX=true
# http://stackoverflow.com/questions/2013547/assigning-default-values-to-shell-variables-with-a-single-command-in-bash
MY_EMAIL=${MY_EMAIL:-github@benjaminfleischer.com}
export DOTFILES_HOME=${DOTFILES_HOME:-.homesick/repos/dotfiles/home}

# set -e

source "$HOME/${DOTFILES_HOME}/../functions.bash"

if [ "$WORKSTATION_UPDATE" = "true" ]
then
  # copy existing files over from home
  # cd ~ && \
  # ls -al | awk '{ print $9 }' | ruby -e 'STDIN.readlines.each{|line| puts(line) \
  #   if line =~ /^\.[a-z_-]+/  \
  #   && File.file?(File.join(File.expand_path("~"),line.chomp)) }' | \
  #   while read "x" ; do cp "$x" "${DOTFILES_HOME}/$x" ; done

  mkdir -p "$HOME/bin"
  cd "$HOME/${DOTFILES_HOME}/.." && \
    #
    # hard link bin files
    git  ls-files bin | \
    ruby -rfileutils -e 'STDIN.readlines.each{|line| \
    FileUtils.ln(File.join(Dir.pwd, line.chomp), File.join(File.expand_path("~"), line.chomp), \
    :verbose => true, :force => true) }'  &&

    # hard link dotfiles
    # prefer homesick
    # git ls-files | \
    # ruby -rfileutils -e 'STDIN.readlines.each{|line| \
    # FileUtils.ln(File.join(Dir.pwd, line.chomp), File.join(File.expand_path("~"), line.chomp), \
    # :verbose => true, :force => true) \
    # if line =~ /^\.[a-z_-]+/  \
    # }'
  echo "setuping up vim" &&
    sh setup_vim.sh
fi


# http://brew.sh/ Homebrew
# if fn_exists "brew"
# if ! command -v brew >/dev/null; then
#   fancy_echo "Installing Homebrew ..."
#     curl -fsS \
#       'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
#
#     append_to_zshrc '# recommended by brew doctor'
#
#     # shellcheck disable=SC2016
#     append_to_zshrc 'export PATH="/usr/local/bin:$PATH"' 1
#
#     export PATH="/usr/local/bin:$PATH"
# else
#   fancy_echo "Homebrew already installed. Skipping ..."
# fi
#
# brew_tap 'thoughtbot/formulae'


# if [ "$WORKSTATION_UPDATE" = "true" ] ; then brew update ; fi
fancy_echo "Updating Homebrew formulas ..."
brew update

# XCode, installed from app store or
#   \curl http://adcdownload.apple.com/Developer_Tools/xcode_5.0.2/xcode_5.0.2.dmg
# then install command line tools
# sudo xcodebuild -license
if fn_exists "xcode-select" && ! fn_exists "clang"
then
 `open /Applications/Xcode.app`
  xcode-select --install
fi

## RVM
## http://rvm.io/
# # work around missing libgmp bug in binary ruby
# brew rm cloog; brew install cloog
install_rvm stable --autolibs=homebrew
install_ruby 2.1 bundler foreman
rvm use 2.1 --default

if [ "$WORKSTATION_UPDATE" = "true" ]
then
  echo "updating rvm"
  rvm get stable --auto-dotfiles &> /dev/null || echo $!
fi

## Git
if fn_exists "git"
then
  echo "we have git"
else
  brew_install "git"
  # The OS X keychain credential helper has been installed to:
  #   /usr/local/bin/git-credential-osxkeychain
  #
  # The 'contrib' directory has been installed to:
  #   /usr/local/share/git-core/contrib
  #
  # Bash completion has been installed to:
  #   /usr/local/etc/bash_completion.d
  #
  # zsh completion has been installed to:
  #   /usr/local/share/zsh/site-functions
  # see https://github.com/thoughtbot/laptop/issues/360
  # ssh keys to github
  ssh git@github.com 2>&1| grep successfully
  if [ $? -eq 0 ]
  then
    "You are authenticated with github"
  else
    if not_file_exists $HOME/.ssh/id_rsa.pub
    then
      mkdir -p ~/.ssh
      cd ~/.ssh
      ssh-keygen -t rsa -C "${MY_EMAIL}"
      # start ssh agent
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_rsa
      echo "Copy your SSH keys to github if you have not already"
      echo "See http://help.github.com/mac-set-up-git/"
      echo "Or just:"
      echo "cat ~/.ssh/id_rsa.pub | pbcopy"
    fi
  fi
  ssh -T git@github.com
fi

## BREWS
# Bundler for managing Ruby libraries
# Exuberant Ctags for indexing files for vim tab completion
# Foreman for managing web processes
# hub for interacting with the GitHub API
# Heroku Toolbelt for interacting with the Heroku API
# Homebrew for managing operating system libraries
# ImageMagick for cropping and resizing images
# Node.js and NPM, for running apps and installing JavaScript packages
# Postgres for storing relational data
# Qt for headless JavaScript testing via Capybara Webkit
# Rbenv for managing versions of Ruby
# RCM for managing company and personal dotfiles
# Redis for storing key-value data
# Ruby Build for installing Rubies
# Ruby stable for writing general-purpose code
# The Silver Searcher for finding things in files
# Tmux for saving project state and switching between projects
# Zsh as your shell

# brew_install_or_upgrade 'git'
# brew_install_or_upgrade 'postgres'

# brew_launchctl_restart 'postgresql'
# brew_install_or_upgrade 'redis'
# brew_launchctl_restart 'redis'
# brew_install_or_upgrade 'the_silver_searcher'
# brew_install_or_upgrade 'vim'
# brew_install_or_upgrade 'ctags'
# brew_install_or_upgrade 'tmux'
# brew_install_or_upgrade 'reattach-to-user-namespace'
# brew_install_or_upgrade 'imagemagick'
# brew_install_or_upgrade 'qt'
# brew_install_or_upgrade 'hub'
# brew_install_or_upgrade 'node'
#
# brew_install_or_upgrade 'rbenv'
# brew_install_or_upgrade 'ruby-build'
#
# # shellcheck disable=SC2016
# append_to_zshrc 'eval "$(rbenv init - zsh --no-rehash)"' 1
#
# brew_install_or_upgrade 'openssl'
# brew unlink openssl && brew link openssl --force
# brew_install_or_upgrade 'libyaml'

# ruby_version="$(curl -sSL http://ruby.thoughtbot.com/latest)"
#
# eval "$(rbenv init - zsh)"

# if ! rbenv versions | grep -Fq "$ruby_version"; then
#   rbenv install -s "$ruby_version"
# fi
#
# rbenv global "$ruby_version"
# rbenv shell "$ruby_version"
#
# gem update --system
#
# gem_install_or_update 'bundler'

# fancy_echo "Configuring Bundler ..."
#   number_of_cores=$(sysctl -n hw.ncpu)
#   bundle config --global jobs $((number_of_cores - 1))

# brew_install_or_upgrade 'heroku-toolbelt'


# skip with parity
# if ! command -v rcup >/dev/null; then
#   brew_tap 'thoughtbot/formulae'
#   brew_install_or_upgrade 'rcm'
# fi
#
# if [ -f "$HOME/.laptop.local" ]; then
#   . "$HOME/.laptop.local"

# brew_tap 'caskroom/cask'
# brew_install_or_upgrade 'brew-cask'
#
# brew cask install dropbox
# brew cask install google-chrome
# brew cask install rdio
#
# gem_install_or_update 'parity'
#
# brew_install_or_upgrade 'tree'
# brew_install_or_upgrade 'watch'

# Follow shell style guidelines by using ShellCheck and Syntastic.
# http://www.shellcheck.net/about.html
# https://github.com/scrooloose/syntastic
brew_install shellcheck
# fi
# see https://github.com/thoughtbot/laptop/pull/372 re: gnupgp
#  brew_install_or_upgrade 'gpg2'
# see https://github.com/thoughtbot/laptop/pull/391
#  brew_install_or_upgrade 'rbenv-gem-rehash'


if cmd_success brew_install "hub"
then
  echo "See https://github.com/github/hub for what hub adds to git"
fi

# get the nice vim that macvim comes with
echo "This may fail if you haven't installed the full XCode."
brew_install macvim

brew_install ctags
brew_install tmux

brew_install reattach-to-user-namespace --wrap-pbcopy-and-pbpaste --wrap-launchtl && echo "Run tmux kill-server"
brew_install the_platinum_searcher # aka 'pt'

brew_install "tree" --app-dir="/Applications"
brew_install "trash" --app-dir="/Applications"

# cabextract
# cmake
# elasticsearch
# erlang
# exercism
# ghi
# graphviz
# imagemagick
# libevent
# libgit2
# maven
# node
# openssl
# ossp-uuid
# pcre
# pkg-config
# postgresql
# readline
# redis
# scala
brew_install terminal-notifier
# the_silver_searcher
# wget
# wine
# winetricks
# youtube-dl

# ack
# apple-gcc42
# bazaar
# beanstalk
# brew-cask
# cabal-install
# chruby
# cscope
# curl
# curl-ca-bundle
# cvs
# d-bus
# doxygen
# dvdbackup
# elinks
# emacs
# faac
# ffmpeg
# flasm
# flex
# fortune
# freetype
# fswatch
# gcc
# gdbm
# gdk-pixbuf
# geoip
# gettext
# ghc
# git
# glew
# glib
# gnupg
# gnutls
# go
# gobject-introspection
# gource
# gtk+
# harfbuzz
# htmldoc
# htop-osx
# icu4c
# intltool
# irssi
# jp2a
# jpeg
# lame
# leiningen
# libevent
# libffi
# lynx
# nettle
# nginx
# nvm
# openjpeg
# phantomjs
# poppler
# ppl011
# pv
# python
# python3
# qt
# rbenv
# rtmpdump
# ruby-build
# source-highlight
# sqlite
# texi2html
# the_platinum_searcher
# tmate
# tor
# unixodbc
# wemux
# wxmac
# x264
# xvid
# xz
# yasm

## Homebrew Cask (for binaries)
brew_tap caskroom/cask
brew_install "brew-cask"

brew_cask "google-chrome" --appdir="/Applications"
# brew_cask sequel-pro --app-dir="/Applications"
# lunchy-go
brew_cask lunchy

brew_cask "caffeine" --app-dir="/Applications"
# TODO: add to login items

brew_cask "cd-to" --app-dir="/Applications"
# TODO: add instructions for dragging link to finder
brew_cask "nvalt" --app-dir="/Applications"
# brew_cask "adium"" --app-dir="/Applications"
# brew_cask "atom" --app-dir="/Applications"
# brew_cask "audacity" --app-dir="/Applications"
# brew_cask "boot2docker" --app-dir="/Applications"
# brew_cask "calibre" --app-dir="/Applications"
# brew_cask "cyberduck" --app-dir="/Applications"
# brew_cask "fluid" --app-dir="/Applications"
# brew_cask "github" --app-dir="/Applications"
# brew_cask "google-drive" --app-dir="/Applications"
# brew_cask "hipchat" --app-dir="/Applications"
# brew_cask "istat-menus" --app-dir="/Applications"
brew_cask "iterm2" --app-dir="/Applications"
# brew_cask "java" --app-dir="/Applications"
brew_cask "keka" --app-dir="/Applications"
# brew_cask "launchrocket" --app-dir="/Applications"
# brew_cask "libreoffice" --app-dir="/Applications"
# brew_cask "minecraft" --app-dir="/Applications"
# brew_cask "netnewswire" --app-dir="/Applications"
# brew_cask "onyx" --app-dir="/Applications"
# brew_cask "osxfuse" --app-dir="/Applications"
brew_cask "pgadmin3" --app-dir="/Applications"
# brew_cask "picasa" --app-dir="/Applications"
# brew_cask "postgres" --app-dir="/Applications"
brew_cask "quiterss" --app-dir="/Applications"
brew_cask "racket" --app-dir="/Applications"
brew_cask "slack" --app-dir="/Applications"
brew_cask "sqlitebrowser" --app-dir="/Applications"
# brew_cask "sublime-text" --app-dir="/Applications"
# brew_cask "tcpblock" --app-dir="/Applications"
# brew_cask "tunnelblick" --app-dir="/Applications"
brew_cask "vagrant" --app-dir="/Applications"
brew_cask "virtualbox" --app-dir="/Applications"
# brew_cask "vmware-fusion" --app-dir="/Applications"
# brew_cask "wireshark" --app-dir="/Applications"
brew_cask "xquartz" --app-dir="/Applications"

if brew cask list | grep "firefox" &> /dev/null
then
  echo "Firefox is already installed by brew cask"
  echo "  If you have trouble running selenium,"
  echo "  brew cask uninstall firefox && workstation setup"
  false
elif app_exists $(echo "Firefox" | cut -d- -f2)
then
  echo "Firefox is installed, but not by brew cask"
  echo "  If you have trouble running selenium, uninstall"
  echo "  and re-run workstation setup"
  false
else
  echo "Installing FireFox"
  # need specific firefox version for selenium tests
  # and need the appdir to be /Applications
  brew cask install ~/${DOTFILES_HOME}/../brews/firefox.rb --appdir="/Applications"
  echo "------"
  echo "------ Selenium Compatible FIREFOX INSTALLED"
  echo "------ Automatic updates are disabled."
  echo "------ You may manually update FireFox if you wish"
  echo "------ Although this may break Capybara tests"
  echo "------"
fi


brew_cask "alfred" --app-dir="/Applications"
echo "open alfred from '/opt/hombrew-cask/Caskroom'"
if cmd_success
then
  # ==> Symlinking App 'Alfred 2.app' to '$HOME/Applications/Alfred
  # 2.app'
  # ==> Symlinking App 'Alfred Preferences.app' to
  # '$HOME/Applications/Alfred Preferences.app'
  # tell alfred find homebrew_casked items
  brew_cask "alfred link"
  # TODO: add to login items
fi


## Repos Directory
if file_exists $HOME/projects
then
  echo "$HOME/projects exists"
else
  echo "Creating $HOME/projects"
  mkdir -p $HOME/projects
fi

# see https://github.com/mathiasbynens/dotfiles/blob/master/.osx

if [ "$HACK_MY_OSX" = "true" ]
then
    # Ask for the administrator password upfront
    sudo -v

    # Keep-alive: update existing `sudo` time stamp until `.osx` has finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

    ###############################################################################
    # General UI/UX                                                               #
    ###############################################################################

    # Set computer name (as done via System Preferences → Sharing)
    #sudo scutil --set ComputerName "0x6D746873"
    #sudo scutil --set HostName "0x6D746873"
    #sudo scutil --set LocalHostName "0x6D746873"
    #sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "0x6D746873"

    # Disable smart quotes as they’re annoying when typing code
    defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

    # Disable smart dashes as they’re annoying when typing code
    defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

    # Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

    # Display ASCII control characters using caret notation in standard text views
    # Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
    defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

    # Reveal IP address, hostname, OS version, etc. when clicking the clock
    # in the login window
    sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

    # Restart automatically if the computer freezes
    sudo systemsetup -setrestartfreeze on

    # Set a custom wallpaper image. `DefaultDesktop.jpg` is already a symlink, and
    # all wallpapers are in `/Library/Desktop Pictures/`. The default is `Wave.jpg`.
    #rm -rf ~/Library/Application Support/Dock/desktoppicture.db
    #sudo rm -rf /System/Library/CoreServices/DefaultDesktop.jpg
    #sudo ln -s /path/to/your/image /System/Library/CoreServices/DefaultDesktop.jpg

    # Increase sound quality for Bluetooth headphones/headsets
    defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

    # Enable full keyboard access for all controls
    # (e.g. enable Tab in modal dialogs)
    defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

    # Disable press-and-hold for keys in favor of key repeat
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

    # Set a blazingly fast keyboard repeat rate
    defaults write NSGlobalDomain KeyRepeat -int 0

    # Disable auto-correct
    defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

    # Menu bar: hide the Time Machine, Volume, User, and Bluetooth icons
    # for domain in ~/Library/Preferences/ByHost/com.apple.systemuiserver.*; do
    #     defaults write "${domain}" dontAutoLoad -array \
    #         "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
    #         "/System/Library/CoreServices/Menu Extras/Volume.menu" \
    #         "/System/Library/CoreServices/Menu Extras/User.menu"
    # done
    # defaults write com.apple.systemuiserver menuExtras -array \
    #     "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
    #     "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
    #     "/System/Library/CoreServices/Menu Extras/Battery.menu" \
    #     "/System/Library/CoreServices/Menu Extras/Clock.menu"

    ###############################################################################
    # SSD-specific tweaks                                                         #
    ###############################################################################

    # Disable local Time Machine snapshots
    sudo tmutil disablelocal

    # Disable hibernation (speeds up entering sleep mode)
    sudo pmset -a hibernatemode 0

    # Remove the sleep image file to save disk space
    sudo rm /Private/var/vm/sleepimage
    # Create a zero-byte file instead…
    sudo touch /Private/var/vm/sleepimage
    # …and make sure it can’t be rewritten
    sudo chflags uchg /Private/var/vm/sleepimage

    # Disable the sudden motion sensor as it’s not useful for SSDs
    sudo pmset -a sms 0

    ## Terminal.app
    # Only use UTF-8 in Terminal.app
    defaults write com.apple.terminal StringEncodings -array 4

    ## Chrome

    # Allow installing user scripts via GitHub Gist or Userscripts.org
    defaults write com.google.Chrome ExtensionInstallSources -array "https://gist.githubusercontent.com/" "http://userscripts.org/*"
    defaults write com.google.Chrome.canary ExtensionInstallSources -array "https://gist.githubusercontent.com/" "http://userscripts.org/*"

    ## Sublime

    # Install Sublime Text settings
    cp -r init/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings 2> /dev/null

    ## Twitter
    # Disable smart quotes as it’s annoying for code tweets
    defaults write com.twitter.twitter-mac AutomaticQuoteSubstitutionEnabled -bool false

    ###############################################################################
    # Safari & WebKit                                                             #
    ###############################################################################

    # Set Safari’s home page to `about:blank` for faster loading
    defaults write com.apple.Safari HomePage -string "about:blank"

    # Prevent Safari from opening ‘safe’ files automatically after downloading
    defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

    # Allow hitting the Backspace key to go to the previous page in history
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

    # Hide Safari’s bookmarks bar by default
    defaults write com.apple.Safari ShowFavoritesBar -bool false

    # Hide Safari’s sidebar in Top Sites
    defaults write com.apple.Safari ShowSidebarInTopSites -bool false

    # Disable Safari’s thumbnail cache for History and Top Sites
    defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

    # Enable Safari’s debug menu
    defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

    # Make Safari’s search banners default to Contains instead of Starts With
    defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

    # Remove useless icons from Safari’s bookmarks bar
    defaults write com.apple.Safari ProxiesInBookmarksBar "()"

    # Enable the Develop menu and the Web Inspector in Safari
    defaults write com.apple.Safari IncludeDevelopMenu -bool true
    defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

    # Add a context menu item for showing the Web Inspector in web views
    defaults write NSGlobalDomain WebK

    ###############################################################################
    # Kill affected applications                                                  #
    ###############################################################################

    # for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
    #     "Dock" "Finder" "Mail" "Messages" "Safari" "SizeUp" "SystemUIServer" \
    #     "Terminal" "Transmission" "Twitter" "iCal"; do
    #     killall "${app}" > /dev/null 2>&1
    # done
    # echo "Done. Note that some of these changes require a logout/restart to take effect."
fi
