#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"

dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
    ctags \
    --tag-relative -L - -f"$dir/$$.tags" \
    --languages=-sql
trap 'rm -f "$dir/$$.gems.tags"' EXIT
ctags \
  -R \
  --languages=ruby \
  --fields=+l \
  -f"$dir/$$.gems.tags" \
  --tag-relative=yes \
  --exclude=.git \
  --exclude=spec \
  --exclude=test \
  --exclude=vendor \
  --exclude=log \
  . \
    $(bundle list --paths)
cat "$dir/$$.gems.tags" >> "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
