#!/bin/sh

DEBUG="${DEBUG:-false}"
GIT_SKIP_CHECKOUT_HOOKS="${GIT_SKIP_CHECKOUT_HOOKS:-false}"
debug()   { if [ "$DEBUG" = "true" ]; then echo "[DEBUG] $*" >&2 ; fi ; }

for hook in "$HOME"/.git_template.local/hooks/post-checkout .git_template.local/hooks/post-checkout; do
  if [ -f "$hook" ]; then
    if [ "${GIT_SKIP_CHECKOUT_HOOKS}" = "true" ]; then
      debug "skipping $hook"
    else
      debug "$hook";
      . "$hook"
    fi
  else
    debug "no such hook ${hook}"
  fi
done
